require 'spec_helper'

describe HmacSignature do
  it 'has the correct version number' do
    expect(HmacSignature::VERSION).to eq('0.1.0')
  end
end

describe HmacSignature::HMAC256 do
  describe 'generate' do
    let(:secret) { 'test_secret' }
    let(:username) { 'john.appleseed@teamsquare.co' }
    let(:timestamp) { Time.utc(2000, 2, 22, 1, 15, 29).to_i }
    let(:key_password) { 'test_password' }

    let(:expected_signature) { '169608eb80e3854956ea2ca39c39fee001133fac76cb42943a86f7596c6aa9fe' }

    it 'generates an HMAC digest using sha256 based on the shared secret provided and string generated by the ' +
           'provided username, timestamp and key password' do
      expect(HmacSignature::HMAC256.generate(secret, username, timestamp, key_password)).to eq(expected_signature)
    end
  end
end